#!/bin/bash
# Cabeçalho
# ----------------------------------------------------------------------------
# Faz backup usando com comando rsync do unix. 
# Configurações são feitas no arquivo de configuração: backup_maker.config
#
# Uso: backup_maker.sh 
# Ex.: ./backup_maker.sh
#
# Autor: Frank <frankcbjunior (a) gmail com>
# Desde: 20-8-2013
# Versão: 1
# ----------------------------------------------------------------------------

# Variáveis
# ----------------------------------------------------------------------------
# TODO: melhorar esse acesso aos arquivos de parser, e de configuração
CONFIG="backup_maker.config" 		# arquivo de configuração
PARSER_FILE="parser"				# arquivo de parser

# Configurações padrões
RSYNC_PARAMS="ax"					# parametros padrões e obrigatórios para o rsync
CONF_VERBOSE="0"					# config: Verbose
CONF_PROGRESSO="0"					# config: Progresso
CONF_DELETE="0"						# config: Delete
CONF_CHECKSUM="0"					# config: Checksum

# Variaveis auxiliares
CHAVES=""							# pega todas as chaves do arquivo de configuração
# ----------------------------------------------------------------------------


# funções
# ----------------------------------------------------------------------------
# funcão para pegar o valor da chave procurada
function retorna_valor(){
chaves=$1
chave=$2
valor=""

# filtrando a saída pela chave que foi passada por parametro
valor=$(echo -e "$chaves" | grep -i "$chave")

# validação, para chave duplicada
if [ $(echo -e "$valor" | wc -l) -gt 1 ]; then
       echo Erro: chave $PARAM duplicada, no arquivo de configuração
       exit 1
fi

# pegando a somente o valor da chave, e imprimindo na saída padrão
valor=$(echo "$valor" | cut -d "=" -f2 | sed 's/\"//g' | tr A-Z a-z)

echo "$valor"
}

# função para validar a chave, e setar o valor correto dela
function valida_chaves(){
chave="$1"

if [ "$chave" = 'on' ] || [ "$chave" = "1" ];then
		chave="$2"
else
		chave=""
fi

echo "$chave"
}
# ----------------------------------------------------------------------------


# Main
# ----------------------------------------------------------------------------
# verificando se o arquivo de configuração existe
# TODO: criar um arquivo de configuração padrão, caso não exista
if [ ! -e "$CONFIG" ];then
	echo ""$CONFIG" não existe"
	exit 1
fi
# Carregando a configuração do arquivo externo
CHAVES="$(./"$PARSER_FILE" "$CONFIG")"

# consultando as chaves
CONF_VERBOSE=$(retorna_valor "$CHAVES" "verbose")
CONF_PROGRESSO=$(retorna_valor "$CHAVES" "progresso")
CONF_CHECKSUM=$(retorna_valor "$CHAVES" "checksum")
CONF_DELETE=$(retorna_valor "$CHAVES" "delete")

# validando as chaves
CONF_VERBOSE=$(valida_chaves "$CONF_VERBOSE" "vh")
CONF_PROGRESSO=$(valida_chaves "$CONF_PROGRESSO" "P")
CONF_CHECKSUM=$(valida_chaves "$CONF_DELETE" "c")
CONF_DELETE=$(valida_chaves "$CONF_DELETE" "--delete")

# agrupando todos os parametros do rsync
RSYNC_PARAMS="$RSYNC_PARAMS$CONF_VERBOSE$CONF_PROGRESSO$CONF_CHECKSUM $CONF_DELETE"
echo "rsync -"$RSYNC_PARAMS" <origem> <destino>"

# ----------------------------------------------------------------------------
