#!/bin/bash
# ----------------------------------------------------------------------------
# parser para ler arquivos de configuração retornando somente as flags
#
# Uso: parser.sh <file.config>
# Ex.: ./parser.sh backup_maker.config
#
# Autor: Frank <frankcbjunior (a) gmail com>
# Desde: 20-8-2013
# Versão: 1
# ----------------------------------------------------------------------------

# Variáveis
# ----------------------------------------------------------------------------
# O arquivo de configuração é indicado na linha de comando
CONFIG=$1

chave=""
valor=""
retorno=""

# funções
# ----------------------------------------------------------------------------
# função com o loop para extrais dados de arquivos de configuração
parser_config(){
# Loop para ler a linha de configuração, guardando em $LINHA
while read LINHA; do

		# Ignorando as linhas de comentário
		[ "$(echo $LINHA | cut -c1)" = '#' ] && continue

		# Ignorando linhas em branco
		[ "$LINHA" ] || continue

		# Guardando cada palavra da linha em $1, $2, $3...
		set - $LINHA

		# Extraindo os dados (chaves sempre maiusculas)
		chave=$(echo $1 | tr a-z A-Z)
		shift
		valor=$*

		# capturando cada linha do arquivo (chave e valor) e atribuindo a variavel $retorno
		# o sed esta retirando os comentários de 1 linha
		echo -e "$retorno$chave=\"$valor\"" | sed 's/\ #.*/"/g'

done < "$CONFIG"
}

# função para extrair os diretorios de origens do arquivo 'origens.txt'
parser_origens(){
# Loop para ler a linha de configuração, guardando em $LINHA
while read LINHA; do

		# Ignorando as linhas de comentário
		[ "$(echo $LINHA | cut -c1)" = '#' ] && continue

		# Ignorando linhas em branco
		[ "$LINHA" ] || continue

		# Guardando cada palavra da linha em $1, $2, $3...
		set - $LINHA

		# Extraindo os dados (chaves sempre maiusculas)
		chave=$(echo $1)

		# capturando cada linha do arquivo (chave e valor) e atribuindo a variavel $retorno
		# o sed esta retirando os comentários de 1 linha
		echo -e "$retorno$chave" | sed 's/\ #.*/"/g'

done < "$CONFIG"
}

# Main
# ----------------------------------------------------------------------------
# O arquivo deve existir e ser legível
if [ -z "$CONFIG" ]; then
		echo uso: parser arquivo.conf
		exit 1
elif [ ! -r "$CONFIG" ]; then
		echo Erro: Não consigo ler o arquivo $CONFIG
		exit 1
fi

if [ "$CONFIG" = 'origens.txt' ];then
	parser_origens
else
	parser_config
fi

